// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RunningApp.Persistence;

#nullable disable

namespace RunningApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810133753_Phase4M2AdaptationPersistenceLineageAndDecisionRecords")]
    partial class Phase4M2AdaptationPersistenceLineageAndDecisionRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RunningApp.Domain.Entities.AdaptationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AffectedDaysJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExplanationKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TriggeredByTrainingDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InternalUserId");

                    b.HasIndex("TriggeredByTrainingDayId");

                    b.HasIndex("PlanId", "CreatedAt")
                        .HasDatabaseName("IX_AdaptationEvents_PlanId_CreatedAt");

                    b.ToTable("AdaptationEvents");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.DailyTipSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoalType")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkoutType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DailyTipSets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "en",
                            Message = "Today is about showing up, not pushing hard.",
                            TipKey = "easy_run_tip_01",
                            Title = "Keep it comfortable",
                            WorkoutType = "easy"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "en",
                            Message = "A long run should feel conversational. Keep it steady.",
                            TipKey = "long_run_tip_01",
                            Title = "Find your rhythm",
                            WorkoutType = "long_run"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "en",
                            Message = "Recovery is when the magic happens. Let your body heal.",
                            TipKey = "rest_tip_01",
                            Title = "Rest with intent",
                            WorkoutType = "rest"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "en",
                            Message = "Taking a day off is part of a sustainable plan.",
                            TipKey = "missed_tip_01",
                            Title = "No worries"
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "en",
                            Message = "Awesome job today. Remember to hydrate and stretch.",
                            TipKey = "completed_tip_01",
                            Title = "Well run!"
                        });
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonActivationWindowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckpointDecisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContextVersionSequence")
                        .HasColumnType("integer");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CoreContextId")
                        .HasColumnType("uuid");

                    b.Property<int>("EndGlobalWeek")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("RunwayPrescriptionId")
                        .HasColumnType("text");

                    b.Property<int>("StartGlobalWeek")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetLockId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonActivationWindowRecords_IdempotencyKey");

                    b.HasIndex("PlanStateId", "StartGlobalWeek", "EndGlobalWeek")
                        .HasDatabaseName("IX_LongHorizonActivationWindowRecords_PlanStateId_Range");

                    b.ToTable("LongHorizonActivationWindowRecords");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonAdaptationDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplacementSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SafetyReviewRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("SourceWindowEndWeek")
                        .HasColumnType("integer");

                    b.Property<int>("SourceWindowStartWeek")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupersededSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TriggerSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanStateId");

                    b.HasIndex("ReplacementSessionId");

                    b.HasIndex("SupersededSessionId");

                    b.HasIndex("TriggerSessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonAdaptationDecisionRecords_TriggerSessionId");

                    b.ToTable("LongHorizonAdaptationDecisionRecords");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonBlockRetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlockedGlobalWeekEnd")
                        .HasColumnType("integer");

                    b.Property<int>("BlockedGlobalWeekStart")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CheckpointDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalReasonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicReasonCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedDecisionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RetryEligible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PlanStateId", "CreatedAtUtc")
                        .HasDatabaseName("IX_LongHorizonBlockRetryRecords_PlanStateId_CreatedAtUtc");

                    b.ToTable("LongHorizonBlockRetryRecords");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonCheckpointRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("AuthoritativeReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("AuthorityClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CompletedFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("ContextVersionSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersistenceVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanStateId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceWindowEndWeek")
                        .HasColumnType("integer");

                    b.Property<int>("SourceWindowStartWeek")
                        .HasColumnType("integer");

                    b.Property<double?>("ValidatedLongRunKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValidatedWeeklyVolumeKm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlanStateId", "AsOfDate", "SourceWindowStartWeek")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonCheckpointRecords_PlanStateId_AsOfDate_Window");

                    b.ToTable("LongHorizonCheckpointRecords");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonCoreContextRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("ConditionResultSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ContextVersionSequence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedDecisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("EffectiveFromGlobalWeek")
                        .HasColumnType("integer");

                    b.Property<int>("EffectiveToGlobalWeek")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceFingerprint")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedCoreResultIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedCoreWeeksPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SupersededByContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidatedLoadAuthoritySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanStateId", "ContextVersionSequence")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonCoreContextRecords_PlanStateId_ContextVersionSequence");

                    b.ToTable("LongHorizonCoreContextRecords");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRollingPlanState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveContextVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveContextVersionSequence")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("BlockedAt")
                        .HasColumnType("date");

                    b.Property<string>("CandidateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogRootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentBlockedInternalReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("CurrentBlockedPublicReasonCategory")
                        .HasColumnType("text");

                    b.Property<string>("CurrentLifecycleStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentWindowEndWeek")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWindowStartWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("GoalDistance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LastActivatedGlobalWeek")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LatestCheckpointDate")
                        .HasColumnType("date");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LongRunDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersistenceContractVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredDaysCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("RaceDate")
                        .HasColumnType("date");

                    b.Property<string>("ReadinessProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RetryEligible")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("LongHorizonRollingPlanStates");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRollingSessionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivationContextVersionSequence")
                        .HasColumnType("integer");

                    b.Property<double?>("ActualDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AdaptedFromSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("NotTodayReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NotTodayRecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Planned")
                        .HasColumnName("CompletionStatus");

                    b.Property<int>("OutcomeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("PlanningStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionOrdinal")
                        .HasColumnType("integer");

                    b.Property<string>("SessionRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WeekStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkoutKey")
                        .HasColumnType("text");

                    b.Property<int?>("WorkoutVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdaptedFromSessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonRollingSessionStates_AdaptedFromSessionId")
                        .HasFilter("\"AdaptedFromSessionId\" IS NOT NULL");

                    b.HasIndex("AssignedDate")
                        .HasDatabaseName("IX_LongHorizonRollingSessionStates_AssignedDate");

                    b.HasIndex("WeekStateId", "SessionOrdinal")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonRollingSessionStates_WeekStateId_SessionOrdinal");

                    b.ToTable("LongHorizonRollingSessionStates");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRollingWeekState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ActivationContextVersionSequence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BlockedDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedReasonCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GlobalWeek")
                        .HasColumnType("integer");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("LongRunKm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("SegmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StructuralEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StructuralStartDate")
                        .HasColumnType("date");

                    b.Property<double?>("WeeklyVolumeKm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlanStateId", "GlobalWeek")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonRollingWeekStates_PlanStateId_GlobalWeek");

                    b.ToTable("LongHorizonRollingWeekStates");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRunwayState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarCompositionIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalendarProjectionPayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<double>("CoreWeekOneLongRunTargetKm")
                        .HasColumnType("double precision");

                    b.Property<double>("CoreWeekOneWeeklyTargetKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullPrescriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FullPrescriptionVersion")
                        .HasColumnType("integer");

                    b.Property<int>("LockedRunwayEndGlobalWeek")
                        .HasColumnType("integer");

                    b.Property<int>("LockedRunwayStartGlobalWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescriptionPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TargetContextVersionSequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetLockId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetLockPayloadJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("PlanStateId")
                        .IsUnique()
                        .HasDatabaseName("IX_LongHorizonRunwayStates_PlanStateId");

                    b.ToTable("LongHorizonRunwayStates");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.NotTodayDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionPayloadJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ResultingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InternalUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TrainingDayId");

                    b.ToTable("NotTodayDecisions");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EveningReminderEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReminderStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("ReminderTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WorkoutRemindersEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InternalUserId");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.PendingConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InternalUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TrainingDayId");

                    b.ToTable("PendingConfirmations");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.PlanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InternalUserId");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_PlanEvents_PlanId");

                    b.ToTable("PlanEvents");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.PlanPreview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConfirmationContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ConfirmedPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutableWindowFingerprint")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsInvalidated")
                        .HasColumnType("boolean");

                    b.Property<string>("LongHorizonInitializationSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LongHorizonPlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedInputFingerprint")
                        .HasColumnType("text");

                    b.Property<string>("PreviewPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("PublicContractVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RollingPersistenceContractVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleStrategy")
                        .HasColumnType("text");

                    b.Property<string>("StructuralRoadmapFingerprint")
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedPlanId")
                        .HasDatabaseName("IX_PlanPreviews_ConfirmedPlanId");

                    b.HasIndex("InternalUserId")
                        .HasDatabaseName("IX_PlanPreviews_InternalUserId");

                    b.ToTable("PlanPreviews");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.PlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoalDistance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.ToTable("PlanTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"templateId\":\"habit_5k_beginner_3day_km_v1\",\"version\":1,\"goalType\":\"habit\",\"goalDistance\":\"five_k\",\"level\":\"beginner\",\"daysPerWeek\":3,\"unit\":\"km\",\"weeks\":[{\"weekNumber\":1,\"weekType\":\"build\",\"days\":[{\"slotIndex\":1,\"dayType\":\"easy\",\"distanceKm\":2.0,\"durationMin\":20,\"intensity\":\"z2\"},{\"slotIndex\":2,\"dayType\":\"easy\",\"distanceKm\":2.5,\"durationMin\":25,\"intensity\":\"z2\"},{\"slotIndex\":3,\"dayType\":\"long_run\",\"distanceKm\":3.0,\"durationMin\":30,\"intensity\":\"z2\"}]}]}",
                            DaysPerWeek = 3,
                            GoalDistance = "five_k",
                            GoalType = "habit",
                            Level = "beginner",
                            TemplateId = "habit_5k_beginner_3day_km_v1",
                            Unit = "km",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"templateId\":\"habit_5k_beginner_4day_km_v1\",\"version\":1,\"goalType\":\"habit\",\"goalDistance\":\"five_k\",\"level\":\"beginner\",\"daysPerWeek\":4,\"unit\":\"km\",\"weeks\":[{\"weekNumber\":1,\"weekType\":\"build\",\"days\":[{\"slotIndex\":1,\"dayType\":\"easy\",\"distanceKm\":2.0,\"durationMin\":20,\"intensity\":\"z2\"},{\"slotIndex\":2,\"dayType\":\"easy\",\"distanceKm\":2.0,\"durationMin\":20,\"intensity\":\"z2\"},{\"slotIndex\":3,\"dayType\":\"easy\",\"distanceKm\":2.5,\"durationMin\":25,\"intensity\":\"z2\"},{\"slotIndex\":4,\"dayType\":\"long_run\",\"distanceKm\":3.0,\"durationMin\":30,\"intensity\":\"z2\"}]}]}",
                            DaysPerWeek = 4,
                            GoalDistance = "five_k",
                            GoalType = "habit",
                            Level = "beginner",
                            TemplateId = "habit_5k_beginner_4day_km_v1",
                            Unit = "km",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"templateId\":\"race_5k_beginner_3day_km_v1\",\"version\":1,\"goalType\":\"race\",\"goalDistance\":\"five_k\",\"level\":\"beginner\",\"daysPerWeek\":3,\"unit\":\"km\",\"weeks\":[{\"weekNumber\":1,\"weekType\":\"build\",\"days\":[{\"slotIndex\":1,\"dayType\":\"easy\",\"distanceKm\":2.5,\"durationMin\":25,\"intensity\":\"z2\"},{\"slotIndex\":2,\"dayType\":\"interval\",\"distanceKm\":3.0,\"durationMin\":30,\"intensity\":\"z4\"},{\"slotIndex\":3,\"dayType\":\"long_run\",\"distanceKm\":4.0,\"durationMin\":40,\"intensity\":\"z2\"}]}]}",
                            DaysPerWeek = 3,
                            GoalDistance = "five_k",
                            GoalType = "race",
                            Level = "beginner",
                            TemplateId = "race_5k_beginner_3day_km_v1",
                            Unit = "km",
                            Version = 1
                        });
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("ActualDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("ActualDurationMin")
                        .HasColumnType("integer");

                    b.Property<double?>("ActualPaceMinKm")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("AdaptedFromId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanMarkComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanMarkNotToday")
                        .HasColumnType("boolean");

                    b.Property<string>("CatalogIntensityKey")
                        .HasColumnType("text");

                    b.Property<string>("CatalogPhaseKey")
                        .HasColumnType("text");

                    b.Property<string>("CatalogPrescriptionJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("CatalogPrescriptionSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogProgressionStageKey")
                        .HasColumnType("text");

                    b.Property<string>("CatalogSlotRole")
                        .HasColumnType("text");

                    b.Property<string>("CatalogStageKey")
                        .HasColumnType("text");

                    b.Property<string>("CatalogStructuralRole")
                        .HasColumnType("text");

                    b.Property<string>("CatalogWorkoutDefinitionKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogWorkoutDefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogWorkoutFamily")
                        .HasColumnType("text");

                    b.Property<string>("CatalogWorkoutKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogWorkoutVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenerationSource")
                        .HasColumnType("text");

                    b.Property<string>("Intensity")
                        .HasColumnType("text");

                    b.Property<bool>("IsLongRun")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OriginalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalType")
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlanVersion")
                        .HasColumnType("integer");

                    b.Property<double>("PlannedDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("PlannedDurationMin")
                        .HasColumnType("integer");

                    b.Property<double?>("PlannedPaceMinKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdaptedFromId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TrainingDays_Status");

                    b.HasIndex("PlanId", "Date");

                    b.HasIndex("WeekId", "Date")
                        .HasDatabaseName("IX_TrainingDays_WeekId_Date");

                    b.ToTable("TrainingDays");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanonicalDistanceFamily")
                        .HasColumnType("text");

                    b.Property<string>("CatalogCandidateKey")
                        .HasColumnType("text");

                    b.Property<string>("CatalogCandidateStatusAtGenerationTime")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogCandidateVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CatalogConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CatalogDependencyVersionsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CatalogLayoutKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogLayoutVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogLevelModifierKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogLevelModifierVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogMaterializerVersion")
                        .HasColumnType("text");

                    b.Property<string>("CatalogPeakVolumeBandPolicyKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogPeakVolumeBandPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogPreviewContentHash")
                        .HasColumnType("text");

                    b.Property<string>("CatalogProgressionModifierKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogProgressionModifierVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogRulePackKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogRulePackVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogRuntimeConditionRegistryKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogRuntimeConditionRegistryVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogTemplateKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogTemplateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogWorkoutProgressionKey")
                        .HasColumnType("text");

                    b.Property<int?>("CatalogWorkoutProgressionVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomDurationWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("CustomGoalType")
                        .HasColumnType("text");

                    b.Property<int?>("CustomTargetTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EstimatedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenerationSource")
                        .HasColumnType("text");

                    b.Property<string>("GoalDistance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("GoalDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HabitPlanType")
                        .HasColumnType("text");

                    b.Property<string>("InjuryNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LongHorizonRollingPlanStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("LongRunDay")
                        .HasColumnType("text");

                    b.Property<string>("PreferredDays")
                        .HasColumnType("text");

                    b.Property<double?>("PreferredPace")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("RaceDate")
                        .HasColumnType("date");

                    b.Property<string>("RaceName")
                        .HasColumnType("text");

                    b.Property<double?>("RequestedTargetDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("ScheduleStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("StaticComplete");

                    b.Property<Guid?>("SourcePreviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TargetFinishTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateId")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WeeklyAvailability")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InternalUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TrainingPlans_InternalUserId_ActiveOnly")
                        .HasFilter("\"Status\" = 'active'");

                    b.HasIndex("LongHorizonRollingPlanStateId")
                        .IsUnique()
                        .HasDatabaseName("IX_TrainingPlans_LongHorizonRollingPlanStateId")
                        .HasFilter("\"LongHorizonRollingPlanStateId\" IS NOT NULL");

                    b.HasIndex("SourcePreviewId")
                        .IsUnique()
                        .HasDatabaseName("IX_TrainingPlans_SourcePreviewId")
                        .HasFilter("\"SourcePreviewId\" IS NOT NULL");

                    b.HasIndex("InternalUserId", "Status")
                        .HasDatabaseName("IX_TrainingPlans_InternalUserId_Status");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualVolumeKm")
                        .HasColumnType("double precision");

                    b.Property<string>("CatalogPhaseKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecoveryWeek")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<double>("PlannedVolumeKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WeekType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "WeekNumber");

                    b.ToTable("TrainingWeeks");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalAuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalAuthProvider", "ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Provider_ExternalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InternalUserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("ActualDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("ActualDurationMin")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TrainingDayId");

                    b.HasIndex("InternalUserId", "CreatedAt")
                        .HasDatabaseName("IX_WorkoutLogs_InternalUserId_CreatedAt");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.AdaptationEvent", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RunningApp.Domain.Entities.TrainingDay", null)
                        .WithMany()
                        .HasForeignKey("TriggeredByTrainingDayId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonActivationWindowRecord", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", null)
                        .WithMany()
                        .HasForeignKey("PlanStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonAdaptationDecisionRecord", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", null)
                        .WithMany()
                        .HasForeignKey("PlanStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingSessionState", null)
                        .WithMany()
                        .HasForeignKey("ReplacementSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingSessionState", null)
                        .WithMany()
                        .HasForeignKey("SupersededSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LongHorizonAdaptationDecisionRecords_LongHorizonRollingSes~1");

                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingSessionState", null)
                        .WithMany()
                        .HasForeignKey("TriggerSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LongHorizonAdaptationDecisionRecords_LongHorizonRollingSes~2");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonBlockRetryRecord", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", null)
                        .WithMany()
                        .HasForeignKey("PlanStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonCheckpointRecord", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", null)
                        .WithMany()
                        .HasForeignKey("PlanStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonCoreContextRecord", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", null)
                        .WithMany()
                        .HasForeignKey("PlanStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRollingSessionState", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingSessionState", null)
                        .WithMany()
                        .HasForeignKey("AdaptedFromSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingWeekState", "Week")
                        .WithMany("Sessions")
                        .HasForeignKey("WeekStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRollingWeekState", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", "Plan")
                        .WithMany("Weeks")
                        .HasForeignKey("PlanStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRunwayState", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", null)
                        .WithMany()
                        .HasForeignKey("PlanStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.NotTodayDecision", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RunningApp.Domain.Entities.TrainingDay", null)
                        .WithMany()
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.NotificationPreference", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.PendingConfirmation", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RunningApp.Domain.Entities.TrainingDay", null)
                        .WithMany()
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.PlanEvent", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.PlanPreview", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingDay", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.TrainingDay", "AdaptedFrom")
                        .WithMany()
                        .HasForeignKey("AdaptedFromId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RunningApp.Domain.Entities.TrainingWeek", "Week")
                        .WithMany("Days")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdaptedFrom");

                    b.Navigation("Plan");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingPlan", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.LongHorizonRollingPlanState", null)
                        .WithMany()
                        .HasForeignKey("LongHorizonRollingPlanStateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingWeek", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", "Plan")
                        .WithMany("Weeks")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("RunningApp.Domain.Entities.UserProfile", "InternalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.HasOne("RunningApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RunningApp.Domain.Entities.TrainingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RunningApp.Domain.Entities.TrainingDay", null)
                        .WithMany()
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRollingPlanState", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.LongHorizonRollingWeekState", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingPlan", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.TrainingWeek", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("RunningApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
