using RunningApp.Domain.Enums;

namespace RunningApp.Domain.Entities;

public class TrainingPlan
{
    public Guid Id { get; set; }
    public Guid? InternalUserId { get; set; }  // FK → Users.Id
    public string? TemplateId { get; set; }
    public TrainingPlanStatus Status { get; set; } = TrainingPlanStatus.Active;
    public GoalType GoalType { get; set; }
    public GoalDistance GoalDistance { get; set; }
    public double? GoalDistanceKm { get; set; }
    public RunningBackground Level { get; set; }
    public int DaysPerWeek { get; set; }
    public DistanceUnit Unit { get; set; } = DistanceUnit.Km;
    public string? RaceName { get; set; }
    public DateOnly? RaceDate { get; set; }
    public int? TargetFinishTimeSeconds { get; set; }
    public DateTime StartedAt { get; set; }
    public DateTime EstimatedEndDate { get; set; }
    public DateTime? CompletedAt { get; set; }
    public DateTime? CancelledAt { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }

    // Onboarding snapshot fields — copied from PlanPreview at confirm time.
    // Template changes must never affect these historical values.
    public string? PreferredDays { get; set; }    // JSON array e.g. "[1,3,5]"
    public int? WeeklyAvailability { get; set; }  // hours per week
    public double? PreferredPace { get; set; }    // min/km comfortable pace
    public string? InjuryNotes { get; set; }

    // Race-specific
    /// <summary>Race akışında long run günü. PreferredDays içinde yer almalı.</summary>
    public string? LongRunDay { get; set; }

    // Habit-specific
    /// <summary>GoalType='habit' olunca zorunlu; race akışında NULL.</summary>
    public string? HabitPlanType { get; set; }

    /// <summary>HabitPlanType='custom' olunca zorunlu.</summary>
    public string? CustomGoalType { get; set; }

    /// <summary>Custom plan için kullanıcının belirlediği hafta sayısı.</summary>
    public int? CustomDurationWeeks { get; set; }

    /// <summary>
    /// CustomGoalType='finish_under_time' hedefi (saniye).
    /// Pace hesabında KULLANILMAZ — motivasyon referansı.
    /// TargetFinishTimeSeconds'dan farklıdır (o race pace zone için).
    /// </summary>
    public int? CustomTargetTimeSeconds { get; set; }

    // Navigation properties
    public ICollection<TrainingWeek> Weeks { get; set; } = new List<TrainingWeek>();

    // ── Backend Integration Phase 3: Process A plan-catalog provenance ──────
    // All nullable/additive. Null for every plan generated by the existing SQL
    // PlanTemplate flow (unchanged). Populated only once a future generation
    // phase actually consumes IPlanCatalogBundleLoader — not populated by any
    // code today. See PHASE3_CATALOG_AWARE_PERSISTENCE.md for the full
    // rationale (why full bundle provenance, why nullable strings, why
    // RequestedTargetDistanceKm is separate from CanonicalDistanceFamily).

    /// <summary>The TEMPLATE_COMBINATION candidate key (e.g. "TEN_K__4D__INTERMEDIATE").</summary>
    public string? CatalogCandidateKey { get; set; }
    public int? CatalogCandidateVersion { get; set; }

    /// <summary>
    /// Snapshot of the candidate's catalog metadata.status (e.g. "DRAFT",
    /// "PUBLISHED") AT THE MOMENT this plan was generated. Deliberately a
    /// point-in-time snapshot, not a live reference — the candidate's status
    /// may change later without altering already-generated plans.
    /// </summary>
    public string? CatalogCandidateStatusAtGenerationTime { get; set; }

    public string? CatalogTemplateKey { get; set; }
    public int? CatalogTemplateVersion { get; set; }

    public string? CatalogLayoutKey { get; set; }
    public int? CatalogLayoutVersion { get; set; }

    public string? CatalogLevelModifierKey { get; set; }
    public int? CatalogLevelModifierVersion { get; set; }

    public string? CatalogWorkoutProgressionKey { get; set; }
    public int? CatalogWorkoutProgressionVersion { get; set; }

    public string? CatalogProgressionModifierKey { get; set; }
    public int? CatalogProgressionModifierVersion { get; set; }

    public string? CatalogRulePackKey { get; set; }
    public int? CatalogRulePackVersion { get; set; }

    public string? CatalogPeakVolumeBandPolicyKey { get; set; }
    public int? CatalogPeakVolumeBandPolicyVersion { get; set; }

    public string? CatalogRuntimeConditionRegistryKey { get; set; }
    public int? CatalogRuntimeConditionRegistryVersion { get; set; }

    /// <summary>
    /// The internal canonical distance family the plan-catalog candidate was
    /// selected under (e.g. "TEN_K"), stored as the catalog's own literal
    /// string rather than mapped onto the existing GoalDistance enum — even
    /// though a lossless mapping happens to exist for this one field today,
    /// per the standing guardrail that catalog vocabulary must be preserved
    /// as catalog identity, not collapsed into backend enums.
    /// </summary>
    public string? CanonicalDistanceFamily { get; set; }

    /// <summary>
    /// The user's exact requested target distance in km (e.g. 8.0 for an "8K"
    /// request), preserved separately from CanonicalDistanceFamily and from
    /// the existing GoalDistanceKm (which is a FIXED, family-representative
    /// constant — see PlanServices.GetGoalDistanceInKm — never the user's
    /// actual custom target). Must never be overwritten by a
    /// family-representative distance (e.g. 8.0 must never become 10.0).
    /// </summary>
    public double? RequestedTargetDistanceKm { get; set; }

    // CatalogBundleHash is deliberately NOT added in this phase: no source
    // file under plan-catalog/catalog/ (the DRAFT source tree the Phase 1
    // loader reads) carries a metadata.contentHash value — that field is only
    // populated at publish/stamp time (CatalogStamper) and stored under
    // plan-catalog/artifacts/, not in the draft source tree. TEN_K__4D__INTERMEDIATE
    // v10 has never been published, so no stable hash is available to the
    // loader today. Deferred until either (a) the loader is extended to also
    // read from a published release/bundle, or (b) Process A publishes v10.
}
