// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtOdzVj68YPKTXMJUZablP872Ffa_55dA',
    appId: '1:313897784498:web:e696716469815e6149a5ab',
    messagingSenderId: '313897784498',
    projectId: 'runner-29739',
    authDomain: 'runner-29739.firebaseapp.com',
    storageBucket: 'runner-29739.firebasestorage.app',
    measurementId: 'G-780P012RYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS2a4J32bYWfwdL5lciKJBLN38wyI13T0',
    appId: '1:313897784498:android:cadeb8d49ea7e0cf49a5ab',
    messagingSenderId: '313897784498',
    projectId: 'runner-29739',
    storageBucket: 'runner-29739.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTk32pV_oX_DfpEjcY3_vGRnEvTnvDKPA',
    appId: '1:313897784498:ios:7a4c23f28403ce0949a5ab',
    messagingSenderId: '313897784498',
    projectId: 'runner-29739',
    storageBucket: 'runner-29739.firebasestorage.app',
    iosClientId: '313897784498-l5k5pjfjfjilrjdv1kt7aigs53j1fpsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.antigravityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTk32pV_oX_DfpEjcY3_vGRnEvTnvDKPA',
    appId: '1:313897784498:ios:7a4c23f28403ce0949a5ab',
    messagingSenderId: '313897784498',
    projectId: 'runner-29739',
    storageBucket: 'runner-29739.firebasestorage.app',
    iosClientId: '313897784498-l5k5pjfjfjilrjdv1kt7aigs53j1fpsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.antigravityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtOdzVj68YPKTXMJUZablP872Ffa_55dA',
    appId: '1:313897784498:web:95df8229ac6a5e3949a5ab',
    messagingSenderId: '313897784498',
    projectId: 'runner-29739',
    authDomain: 'runner-29739.firebaseapp.com',
    storageBucket: 'runner-29739.firebasestorage.app',
    measurementId: 'G-PBVKT0YXZF',
  );
}
